version: '3'

services:
  apollo-backend:
    image: ghcr.io/apollolau/apollo-backend:master
    depends_on:
      - mongo
    environment:
      - APP_ID=frsAppID
      - MASTER_KEY=frsMasterKey
      - SERVER_URL=http://localhost:1337/parse
      - DATABASE_URI=mongodb://root:example@mongo:27017
    ports:
    - "1337:1337"
    tty: true
    volumes:
      - ./cloud:/parse/cloud

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - database-data:/data/db

volumes:
  database-data:



